// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.shopping.stub.order;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shopping.stub.order.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int32 order_id = 2;</code>
   * @return The orderId.
   */
  int getOrderId();

  /**
   * <code>int32 no_of_items = 3;</code>
   * @return The noOfItems.
   */
  int getNoOfItems();

  /**
   * <pre>
   *  google.protobuf.Timestamp order_date = 5; 
   * </pre>
   *
   * <code>double total_amount = 4;</code>
   * @return The totalAmount.
   */
  double getTotalAmount();
}
