// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.shopping.stub.order;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shopping.stub.order.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shopping.stub.order.Order order = 1;</code>
   */
  java.util.List<com.shopping.stub.order.Order> 
      getOrderList();
  /**
   * <code>repeated .com.shopping.stub.order.Order order = 1;</code>
   */
  com.shopping.stub.order.Order getOrder(int index);
  /**
   * <code>repeated .com.shopping.stub.order.Order order = 1;</code>
   */
  int getOrderCount();
  /**
   * <code>repeated .com.shopping.stub.order.Order order = 1;</code>
   */
  java.util.List<? extends com.shopping.stub.order.OrderOrBuilder> 
      getOrderOrBuilderList();
  /**
   * <code>repeated .com.shopping.stub.order.Order order = 1;</code>
   */
  com.shopping.stub.order.OrderOrBuilder getOrderOrBuilder(
      int index);
}
